baseurl = "/"
languageCode = "de-de"
title = "Studio Rijeka"
canonifyUrls = "true"
theme = "landing-page-hugo"

[params]
    description = "Studio Rijeka, im Stadtteil Krimeja"
    custom_css = ["css/local.css"]
    faviconUrl = "favicon-university.ico"

[[params.social]]
    title = "kontakt"
    icon = "envelope-o"
    url = "https://www.airbnb.de/rooms/7867688#host-profile"
[[params.social]]
    title = "airbnb"
    icon = "bed"
    url = "https://www.airbnb.de/rooms/7867688"
[[params.social]]
    title = "reviews"
    icon = "comments-o"
    url = "https://www.airbnb.de/rooms/7867688#reviews"
